package com.sdf.aso.common.db.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.sdf.aso.common.db.entity.Heros;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig herosDaoConfig;

    private final HerosDao herosDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        herosDaoConfig = daoConfigMap.get(HerosDao.class).clone();
        herosDaoConfig.initIdentityScope(type);

        herosDao = new HerosDao(herosDaoConfig, this);

        registerDao(Heros.class, herosDao);
    }
    
    public void clear() {
        herosDaoConfig.getIdentityScope().clear();
    }

    public HerosDao getHerosDao() {
        return herosDao;
    }

}
